In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [7]:
x = df.iloc[:,:-1]   
y = df.iloc[:,-1]  
print(y.shape)
print(type(x))
print(type(y))

(768,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [8]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [11]:
768*0.75

576.0

In [12]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [13]:
def gen_metrics(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('confusion matrix\n',cm)
    print('Classification report\n',classification_report(ytest,ypred))
    print('Acc score',accuracy_score(ytest,ypred))

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
m1 = LogisticRegression(max_iter=1000)
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [16]:
print('Training score',m1.score(x_train,y_train))
print('Testing score',m1.score(x_test,y_test))

Training score 0.7829861111111112
Testing score 0.734375


In [17]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0
 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0
 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0
 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0
 0 0 0 1 0 1 0]


In [18]:
gen_metrics(y_test,ypred_m1)

confusion matrix
 [[108  28]
 [ 23  33]]
Classification report
               precision    recall  f1-score   support

           0       0.82      0.79      0.81       136
           1       0.54      0.59      0.56        56

    accuracy                           0.73       192
   macro avg       0.68      0.69      0.69       192
weighted avg       0.74      0.73      0.74       192

Acc score 0.734375


In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
m2 = KNeighborsClassifier(n_neighbors=17)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [21]:
print('Training score',m2.score(x_train,y_train))
print('Testing score',m2.score(x_test,y_test))

Training score 0.78125
Testing score 0.7291666666666666


In [22]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 1 1
 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0
 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 0 0
 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0
 0 0 0 1 0 1 0]


In [23]:
gen_metrics(y_test,ypred_m2)

confusion matrix
 [[107  29]
 [ 23  33]]
Classification report
               precision    recall  f1-score   support

           0       0.82      0.79      0.80       136
           1       0.53      0.59      0.56        56

    accuracy                           0.73       192
   macro avg       0.68      0.69      0.68       192
weighted avg       0.74      0.73      0.73       192

Acc score 0.7291666666666666


In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
m3 = DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=15)
# 
m3.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=15)

In [26]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))

Training score 0.8368055555555556
Testing score 0.6927083333333334


In [27]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[1 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1
 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0
 0 0 1 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0
 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0
 0 1 0 1 1 1 0]


In [28]:
gen_metrics(y_test,ypred_m3)

confusion matrix
 [[102  34]
 [ 25  31]]
Classification report
               precision    recall  f1-score   support

           0       0.80      0.75      0.78       136
           1       0.48      0.55      0.51        56

    accuracy                           0.69       192
   macro avg       0.64      0.65      0.64       192
weighted avg       0.71      0.69      0.70       192

Acc score 0.6927083333333334


In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
m4 = RandomForestClassifier(n_estimators=50,criterion='entropy',max_depth=6,min_samples_split=12)
m4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_split=12,
                       n_estimators=50)

In [31]:
print('Training score',m4.score(x_train,y_train))
print('Testing score',m4.score(x_test,y_test))

Training score 0.8732638888888888
Testing score 0.7395833333333334


In [32]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0
 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0
 0 0 0 1 0 1 0]


In [33]:
gen_metrics(y_test,ypred_m4)

confusion matrix
 [[109  27]
 [ 23  33]]
Classification report
               precision    recall  f1-score   support

           0       0.83      0.80      0.81       136
           1       0.55      0.59      0.57        56

    accuracy                           0.74       192
   macro avg       0.69      0.70      0.69       192
weighted avg       0.75      0.74      0.74       192

Acc score 0.7395833333333334


In [34]:
from sklearn.svm import SVC

In [35]:
m5 = SVC(kernel='linear',C=1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [36]:
print('Training score',m5.score(x_train,y_train))
print('Testing score',m5.score(x_test,y_test))

Training score 0.7847222222222222
Testing score 0.7291666666666666


In [37]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0
 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0
 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0
 0 0 0 1 0 1 0]


In [38]:
gen_metrics(y_test,ypred_m5)

confusion matrix
 [[109  27]
 [ 25  31]]
Classification report
               precision    recall  f1-score   support

           0       0.81      0.80      0.81       136
           1       0.53      0.55      0.54        56

    accuracy                           0.73       192
   macro avg       0.67      0.68      0.68       192
weighted avg       0.73      0.73      0.73       192

Acc score 0.7291666666666666


In [ ]:
#Conclusion
#1) Log_Reg is the best performining model in terms of accuracy.
#2) Log_Reg and SVC are the best performining model in terms of recall